Created a new notebook for the table append operator
implydata/learn-druid pull request #88
Opened 2024-06-06 15:21 UTC by hevansDev

2024-06-12 11:28 UTC, petermarshallio commented
LGTM @techdocsmith - over to you for a double-check. Looking forward to your grammatical eye!

2024-06-12 11:28 UTC, petermarshallio commented
@hevansDev I'm wondering if we need to keep the update to the README.MD out of this PR until @317brian creates the new docker build? Or if we wait to merge this until the Druid 30 image is pushed? @techdocsmith what do you think?

2024-06-25 18:29 UTC, hevansDev commented
> @hevansDev I'm wondering if we need to keep the update to the README.MD out of this PR until @317brian creates the new docker build? Or if we wait to merge this until the Druid 30 image is pushed? @techdocsmith what do you think?

@317brian  and I are going to build the new image Friday morning GMT, if we merge this afterwards we don't need to remove the reference in README.MD. Alternatively I could remove it and add it along with the complex group by example

2024-06-26 23:16 UTC, techdocsmith requested changes
mostly stylistic suggestions, but there's an unfinished sentence at line 271.  i was on Druid 29 so the code broke for me. Will test again w/ 30 when the image is ready friday, but i didn't see anything weird in the code bits.

2024-06-26 23:16 UTC, techdocsmith commented on notebooks/03-query/17-table-append-operations.ipynb
> +    "TABLE(APPEND) is used to append the contents of one table to the end of another. TABLE(APPEND) respects the schemas of the incoming result sets automatically unlike the [UNION](https://druid.apa
```suggestion
    "As the name suggests, TABLE(APPEND) appends the contents of one table to the end of another. TABLE(APPEND) respects the schemas of the incoming result sets automatically. This makes working with TABLE(APPEND) simpler than using the [UNION](https://druid.apache.org/docs/26.0.0/querying/datasource.html#union) operator which requires you to explicitly specify the schemas for the tables.\n",
    "\n",
    "When schemas differ, TABLE(APPEND) returns NULL columns that do not exist in one table, but do in the other. Druid automatically handles the data types for both tables. When columns of the same name have different data types in different tables, Druid adjusts the data type to be the most permissive to accommodate  all the data in the result set.\n",
```

2024-06-26 23:16 UTC, techdocsmith commented on notebooks/03-query/17-table-append-operations.ipynb
> +    "You can now use TABLE(APPEND) to append one table to another.\n",
```suggestion
    "You can now use TABLE(APPEND) to append results from one example table to results from the other.\n",
```

2024-06-26 23:16 UTC, techdocsmith commented on notebooks/03-query/17-table-append-operations.ipynb
> +    "The first query in the cell below returns the ten first edits in the resulting table which combines both the existing tables. You can see which table each record is orginally from by looking at
```suggestion
    "The first query in the following cell returns the first ten edits from both the example tables. The `tableName` column indicates the source table for each record."
```

2024-06-26 23:16 UTC, techdocsmith commented on notebooks/03-query/17-table-append-operations.ipynb
> +    "Optionally, run the next cell to show the precise [`EXPLAIN PLAN`](https://druid.apache.org/docs/latest/querying/sql-translation#interpreting-explain-plan-output) for the query. There is one `qu
```suggestion
    "Optionally, run the next cell to show the precise [EXPLAIN PLAN](https://druid.apache.org/docs/latest/querying/sql-translation#interpreting-explain-plan-output) for the query. There is one `query` execution plan in addition to Druid's optimized execution planning process of the outer query. For UNION operations, there would be two query plans. "
```
Note that we don't want to put Druid SQL in `code ticks`

2024-06-26 23:16 UTC, techdocsmith commented on notebooks/03-query/17-table-append-operations.ipynb
> +    "Run the below to get the total number of edits made by humans and the total number of edits made by bots. Without TABLE(APPEND) it would be necessary\n",
it would be necessary to ? i think there is text missing.

also note:
'you can' is more concise than 'it is possible to'

2024-06-27 11:41 UTC, hevansDev commented
@techdocsmith made the changes you recommended

2024-07-02 21:09 UTC, techdocsmith approved these changes
LGTM

2024-07-02 21:10 UTC, merged