Update 01-streaming-from-kafka.ipynb
implydata/learn-druid pull request #99
Opened 2024-06-27 13:24 UTC by petermarshallio

Proposed changes to this notebook to apply the revised template for notebooks, simplify some areas (e.g. switch to auto schema ingestion), and give a light introduction to what ingestion specs are.

2024-06-27 13:25 UTC, petermarshallio commented
@techdocsmith tagging you as I believe this was one of your contributions?

2024-07-09 01:14 UTC, techdocsmith requested changes
love the improvements. left a heap of stylistic comments.

2024-07-09 01:14 UTC, techdocsmith commented on notebooks/02-ingestion/01-streaming-from-kafka.ipynb
> +    "Run this next cell to execute the query, store the results (`response`), and display them."
```suggestion
    "Run the next cell to execute the query, store the results (`response`), and display them."
```

2024-07-09 01:14 UTC, techdocsmith commented on notebooks/02-ingestion/01-streaming-from-kafka.ipynb
> +    "Next, the dataframe is plotted."
```suggestion
    "Next, plot the the dataframe."
```

2024-07-09 01:14 UTC, techdocsmith commented on notebooks/02-ingestion/01-streaming-from-kafka.ipynb
> +    "In the next cell, the results are put into a Pandas dataframe and then sorted (the order of users may vary as new results arrive).\n",
```suggestion
    "The next cell stores the results in a Pandas dataframe and then sorts them. Note that the order of users may vary as new results arrive.\n",
```

2024-07-09 01:14 UTC, techdocsmith requested changes
love the improvements. left a heap of stylistic comments.

2024-07-09 07:40 UTC, merged